name: Flutter CI
on:
  push:
    branches: [ "flutterflow" ]
  pull_request:
    branches: [ "flutterflow" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # Configurar Java (muitos projetos Flutter precisam disso)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          cache: true # Ativa o cache para melhorar performance
      
      # Limpa as dependências antigas e força nova instalação
      - name: Clean and get dependencies
        run: |
          flutter clean
          flutter pub cache repair
          flutter pub get
      
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .
      
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test --reporter=expanded
